# Carguen el archivo CSV pokemon_data.csv.

In [1]:
from google.colab import drive
import pandas as pd
import numpy as np
import os

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
path = '/content/drive/MyDrive/Tarea3/'
list_files = os.listdir(path)
list_files

['Pokemon.csv']

In [6]:
df = pd.read_csv('/content/drive/My Drive/Tarea3/Pokemon.csv')
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

# Imprime las primeras 10 filas del df

In [7]:
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

# Muestra el tipo de datos de cada una de las variables.

In [8]:
df.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

# Muestra el número de valores nulos en cada variable.

In [9]:
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

# Filtren los Pokémon que son de tipo 'Fighting' y tienen un Total mayor a 400.

In [11]:
fighting = df[((df["Type 1"] == "Fighting") | (df["Type 2"] == "Fighting")) & (df["Total"] > 400)]
print(fighting)

       #                     Name    Type 1    Type 2  Total   HP  Attack  \
62    57                 Primeape  Fighting       NaN    455   65     105
67    62                Poliwrath     Water  Fighting    510   90      95
73    67                  Machoke  Fighting       NaN    405   80     100
74    68                  Machamp  Fighting       NaN    505   90     130
114  106                Hitmonlee  Fighting       NaN    455   50     120
115  107               Hitmonchan  Fighting       NaN    455   50     105
163  150      MewtwoMega Mewtwo X   Psychic  Fighting    780  106     190
231  214                Heracross       Bug  Fighting    500   80     125
232  214  HeracrossMega Heracross       Bug  Fighting    600   80     185
256  237                Hitmontop  Fighting       NaN    455   50      95
277  256                Combusken      Fire  Fighting    405   60      85
278  257                 Blaziken      Fire  Fighting    530   80     120
279  257    BlazikenMega Blaziken      Fire  Fighting    630   80     160
310  286                  Breloom     Grass  Fighting    460   60     130
321  297                 Hariyama  Fighting       NaN    474  144     120
335  308                 Medicham  Fighting   Psychic    410   60      60
336  308    MedichamMega Medicham  Fighting   Psychic    510   60     100
436  391                 Monferno      Fire  Fighting    405   64      78
437  392                Infernape      Fire  Fighting    534   76     104
476  428      LopunnyMega Lopunny    Normal  Fighting    580   65     136
497  448                  Lucario  Fighting     Steel    525   70     110
498  448      LucarioMega Lucario  Fighting     Steel    625   70     145
504  454                Toxicroak    Poison  Fighting    490   83     106
526  475                  Gallade   Psychic  Fighting    518   68     125
527  475      GalladeMega Gallade   Psychic  Fighting    618   68     165
558  499                  Pignite      Fire  Fighting    418   90      93
559  500                   Emboar      Fire  Fighting    528  110     123
593  533                  Gurdurr  Fighting       NaN    405   85     105
594  534               Conkeldurr  Fighting       NaN    505  105     140
598  538                    Throh  Fighting       NaN    465  120     100
599  539                     Sawk  Fighting       NaN    465   75     125
621  560                  Scrafty      Dark  Fighting    488   65      90
681  620                 Mienshao  Fighting       NaN    510   65     125
699  638                 Cobalion     Steel  Fighting    580   91      90
700  639                Terrakion      Rock  Fighting    580   91     129
701  640                 Virizion     Grass  Fighting    580   91      90
713  647     KeldeoOrdinary Forme     Water  Fighting    580   91      72
714  647     KeldeoResolute Forme     Water  Fighting    580   91      72
716  648  MeloettaPirouette Forme    Normal  Fighting    600  100     128
720  652               Chesnaught     Grass  Fighting    530   88     107
743  675                  Pangoro  Fighting      Dark    495   95     124
771  701                 Hawlucha  Fighting    Flying    500   78      92

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
62        60       60       70     95           1      False
67        95       70       90     70           1      False
73        70       50       60     45           1      False
74        80       65       85     55           1      False
114       53       35      110     87           1      False
115       79       35      110     76           1      False
163      100      154      100    130           1       True
231       75       40       95     85           2      False
232      115       40      105     75           2      False
256       95       35      110     70           2      False
277       60       85       60     55           3      False
278       70      110       70     80           3      False
279       80      130       80    100           3      False
310       80       60       60     70           3      False
321       60       40       60     50           3      False
335       75       60       75     80           3      False
336       85       80       85    100           3      False
436       52       78       52     81           4      False
437       71      104       71    108           4      False
476       94       54       96    135           4      False
497       70      115       70     90           4      False
498       88      140       70    112           4      False
504       65       86       65     85           4      False
526       65       65      115     80           4      False
527       95       65      115    110           4      False
558       55       70       55     55           5      False
559       65      100       65     65           5      False
593       85       40       50     40           5      False
594       95       55       65     45           5      False
598       85       30       85     45           5      False
599       75       30       75     85           5      False
621      115       45      115     58           5      False
681       60       95       60    105           5      False
699      129       90       72    108           5       True
700       90       72       90    108           5       True
701       72       90      129    108           5       True
713       90      129       90    108           5      False
714       90      129       90    108           5      False
716       90       77       77    128           5      False
720      122       74       75     64           6      False
743       78       69       71     58           6      False
771       75       74       63    118           6      False

# Cambien el tipo de dato de la columna 'HP' a entero.

In [12]:
df["HP"] = df["HP"].astype(int)

# Eliminen la columna 'Generation'.

In [13]:
df = df.drop(columns=["Generation"])

# Renombren 'Name' a 'Pokémon' y 'Total' a 'Puntos Totales'.

In [14]:
df = df.rename(columns={"Name": "Pokémon", "Total": "Puntos Totales"})

# Muestren el DataFrame resultante.

In [15]:
print(df)

       #                Pokémon   Type 1  Type 2  Puntos Totales  HP  Attack  \
0      1              Bulbasaur    Grass  Poison             318  45      49
1      2                Ivysaur    Grass  Poison             405  60      62
2      3               Venusaur    Grass  Poison             525  80      82
3      3  VenusaurMega Venusaur    Grass  Poison             625  80     100
4      4             Charmander     Fire     NaN             309  39      52
..   ...                    ...      ...     ...             ...  ..     ...
795  719                Diancie     Rock   Fairy             600  50     100
796  719    DiancieMega Diancie     Rock   Fairy             700  50     160
797  720    HoopaHoopa Confined  Psychic   Ghost             600  80     110
798  720     HoopaHoopa Unbound  Psychic    Dark             680  80     160
799  721              Volcanion     Fire   Water             600  80     110

     Defense  Sp. Atk  Sp. Def  Speed  Legendary
0         49       65       65     45      False
1         63       80       80     60      False
2         83      100      100     80      False
3        123      122      120     80      False
4         43       60       50     65      False
..       ...      ...      ...    ...        ...
795      150      100      150     50       True
796      110      160      110    110       True
797       60      150      130     70       True
798       60      170      130     80       True
799      120      130       90     70       True

[800 rows x 12 columns]