# NUMPY

In [31]:
import numpy as np
import pandas as pd

In [3]:
np.random.random ([5, 2])

array([[0.49334785, 0.09476014],
       [0.0083601 , 0.20847597],
       [0.74628395, 0.90861183],
       [0.54929045, 0.99007848],
       [0.95349199, 0.25335458]])

In [5]:
a = np.random.random ([5, 2])

In [6]:
a.shape

(5, 2)

In [7]:
a.size

10

In [9]:
b = np.random.random([5,2,3])

In [10]:
b.shape

(5, 2, 3)

In [14]:
c = np.random.random([5,5,2,3])

In [15]:
print (c)

[[[[0.46232889 0.53054982 0.6077694 ]
   [0.9133147  0.20679746 0.97611115]]

  [[0.13199032 0.44886778 0.07363438]
   [0.78202825 0.45849496 0.83275254]]

  [[0.55175254 0.04968555 0.36873748]
   [0.74764582 0.18312006 0.51473022]]

  [[0.7437796  0.29063557 0.55505907]
   [0.15007326 0.17243442 0.3422235 ]]

  [[0.51205262 0.35156035 0.06682295]
   [0.5373539  0.61763295 0.2124195 ]]]


 [[[0.77876442 0.70845101 0.90966128]
   [0.22003052 0.65005563 0.75117684]]

  [[0.67342706 0.82303288 0.50670089]
   [0.7535205  0.02513483 0.84325957]]

  [[0.62227376 0.09502421 0.00690011]
   [0.22356831 0.90247219 0.2598149 ]]

  [[0.11500317 0.05824886 0.3628499 ]
   [0.15794054 0.53683587 0.38022658]]

  [[0.12083743 0.62347686 0.23483336]
   [0.7628841  0.81220112 0.35322852]]]


 [[[0.3281537  0.18645095 0.77565503]
   [0.24938277 0.63216935 0.69465171]]

  [[0.70589792 0.21991907 0.94485227]
   [0.29426945 0.829502   0.81015034]]

  [[0.22670289 0.87777627 0.9466011 ]
   [0.63259254 0.89309091 0.92179904]]

  [[0.75267594 0.53583863 0.16104465]
   [0.29248294 0.26145418 0.16357018]]

  [[0.36315421 0.23031042 0.35146141]
   [0.8512013  0.01389482 0.09666205]]]


 [[[0.69389027 0.82953127 0.59900054]
   [0.88543371 0.79922143 0.35212266]]

  [[0.64552331 0.0904975  0.01128723]
   [0.21285084 0.01516582 0.89026147]]

  [[0.13173928 0.59519038 0.79525555]
   [0.80211602 0.91254166 0.65012785]]

  [[0.17968498 0.70867501 0.47715285]
   [0.6365363  0.07555736 0.25930591]]

  [[0.51867341 0.03548493 0.17926481]
   [0.89764526 0.13429084 0.35513523]]]


 [[[0.14694025 0.87283721 0.4374398 ]
   [0.35576656 0.37024306 0.23840799]]

  [[0.11149523 0.09469707 0.08894368]
   [0.96082019 0.99888866 0.39721067]]

  [[0.98155823 0.0745688  0.9802705 ]
   [0.58137949 0.35857279 0.58853361]]

  [[0.29809825 0.71696449 0.72348209]
   [0.4538768  0.1090569  0.89901065]]

  [[0.97400527 0.03370986 0.83591489]
   [0.518256   0.81513112 0.10609152]]]]

In [16]:
c.shape

(5, 5, 2, 3)

In [19]:
print (a)

[[0.28370994 0.09985908]
 [0.56964987 0.5242056 ]
 [0.01305599 0.24371496]
 [0.05072103 0.26187962]
 [0.73279314 0.70756035]]

In [20]:
a [0]

array([0.28370994, 0.09985908])

In [21]:
a [0] [1]

0.09985908154936096

In [22]:
lst_lst = [1, 2, 4], [4, 5, 6], [7, 8, 9]

In [23]:
print (lst_lst)

([1, 2, 4], [4, 5, 6], [7, 8, 9])

In [24]:
lst_array = np.array (lst_lst)

In [25]:
print (lst_array)

[[1 2 4]
 [4 5 6]
 [7 8 9]]

In [26]:
np.sum (lst_array)

46

In [27]:
np.sum (lst_array, axis = 0 ) #suma de cada columna

array([12, 15, 19])

In [28]:
np.sum (lst_array, axis = 1 ) #suma de cada renglon

array([ 7, 15, 24])

# Pandas

In [29]:
import pandas as pd

In [35]:
a = pd.Series(np.random.random(10))

In [36]:
print (a)

0    0.338923
1    0.697239
2    0.742849
3    0.557186
4    0.635240
5    0.582319
6    0.985306
7    0.228925
8    0.628849
9    0.076762
dtype: float64

In [38]:
a [0]

0.33892347279867063

In [39]:
a [:3]

0    0.338923
1    0.697239
2    0.742849
dtype: float64

In [40]:
columns = ["col1", "col2", "col3",]

In [44]:
columns = ["col1", "col2", "col3", "col4", "col5"]
df = pd.DataFrame(np.random.random((10,5)), columns=columns)

In [45]:
print (df)

       col1      col2      col3      col4      col5
0  0.037916  0.693045  0.313835  0.058371  0.074649
1  0.962004  0.052460  0.003465  0.975938  0.860617
2  0.000035  0.558595  0.490547  0.407651  0.905109
3  0.817512  0.966321  0.841919  0.731766  0.636624
4  0.059777  0.709741  0.011428  0.933053  0.178606
5  0.561550  0.686742  0.433198  0.392850  0.999954
6  0.904878  0.220354  0.898087  0.835859  0.186381
7  0.858656  0.052565  0.244802  0.600209  0.582167
8  0.758709  0.010970  0.636311  0.712692  0.338731
9  0.883945  0.872656  0.394174  0.903934  0.387335

In [46]:
df ["col2"]

0    0.693045
1    0.052460
2    0.558595
3    0.966321
4    0.709741
5    0.686742
6    0.220354
7    0.052565
8    0.010970
9    0.872656
Name: col2, dtype: float64

In [47]:
df [["col1", "col2"]]

       col1      col2
0  0.037916  0.693045
1  0.962004  0.052460
2  0.000035  0.558595
3  0.817512  0.966321
4  0.059777  0.709741
5  0.561550  0.686742
6  0.904878  0.220354
7  0.858656  0.052565
8  0.758709  0.010970
9  0.883945  0.872656

In [48]:
df.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5'], dtype='object')

In [50]:
df = df.rename(columns = {"col1": "COL1"})

In [52]:
print (df)

       COL1      col2      col3      col4      col5
0  0.037916  0.693045  0.313835  0.058371  0.074649
1  0.962004  0.052460  0.003465  0.975938  0.860617
2  0.000035  0.558595  0.490547  0.407651  0.905109
3  0.817512  0.966321  0.841919  0.731766  0.636624
4  0.059777  0.709741  0.011428  0.933053  0.178606
5  0.561550  0.686742  0.433198  0.392850  0.999954
6  0.904878  0.220354  0.898087  0.835859  0.186381
7  0.858656  0.052565  0.244802  0.600209  0.582167
8  0.758709  0.010970  0.636311  0.712692  0.338731
9  0.883945  0.872656  0.394174  0.903934  0.387335

In [53]:
lst = [208500, 181500, 223500, 140000, 250000, 143000, 307000, 200000, 129900, 118000]

In [55]:
price_df = pd.DataFrame(lst, columns = ['sales price'])

In [56]:
print (price_df)

   sales price
0       208500
1       181500
2       223500
3       140000
4       250000
5       143000
6       307000
7       200000
8       129900
9       118000

In [59]:
lst_lst = [[8450, 'CollgCr', 2003, 7, 208500],
          [9600, 'Veenker', 1976, 6, 181500],
          [11250, 'CollgCr', 2001, 7, 223500],
          [9550, 'Crawfor', 1915, 7, 140000],
          [14260, 'NoRidge', 2000, 8, 250000],
          [14115, 'Mitchel', 1993, 5, 143000],
          [10084, 'Somerst', 2004, 8, 307000],
          [10382, 'NWAmes', 1973, 7, 200000],
          [6120, 'OldTown', 1931, 7, 129900],
          [7420, 'BrkSide', 1939, 5, 118000]]
cols = ["tamano", "vecindario", "year", "puntaje", "precio"]

pd.DataFrame(lst_lst, columns = cols)

   tamano vecindario  year  puntaje  precio
0    8450    CollgCr  2003        7  208500
1    9600    Veenker  1976        6  181500
2   11250    CollgCr  2001        7  223500
3    9550    Crawfor  1915        7  140000
4   14260    NoRidge  2000        8  250000
5   14115    Mitchel  1993        5  143000
6   10084    Somerst  2004        8  307000
7   10382     NWAmes  1973        7  200000
8    6120    OldTown  1931        7  129900
9    7420    BrkSide  1939        5  118000

In [63]:
house_dict = {'Baker House': [7420, 'BrkSide', 1939, 5, 118000],
             'Beazley House': [14115, 'Mitchel', 1993, 5, 143000],
             'Dominguez House': [14260, 'NoRidge', 2000, 8, 250000],
             'Hamilton House': [6120, 'OldTown', 1931, 7, 129900],
             'James House': [11250, 'CollgCr', 2001, 7, 223500],
             'Martinez House': [9600, 'Veenker', 1976, 6, 181500],
             'Roberts House': [9550, 'Crawfor', 1915, 7, 140000],
             'Smith House': [8450, 'CollgCr', 2003, 7, 208500],
             'Snyder House': [10084, 'Somerst', 2004, 8, 307000],
             'Zuckerman House': [10382, 'NWAmes', 1973, 7, 200000]}
pd.DataFrame(house_dict)

,Baker House,Beazley House,Dominguez House,Hamilton House,James House,Martinez House,Roberts House,Smith House,Snyder House,Zuckerman House
0,7420,14115,14260,6120,11250,9600,9550,8450,10084,10382
1,BrkSide,Mitchel,NoRidge,OldTown,CollgCr,Veenker,Crawfor,CollgCr,Somerst,NWAmes
2,1939,1993,2000,1931,2001,1976,1915,2003,2004,1973
3,5,5,8,7,7,6,7,7,8,7
4,118000,143000,250000,129900,223500,181500,140000,208500,307000,200000

In [64]:
df_dict = pd.DataFrame.from_dict(house_dict, orient='index')


df_dict.columns = cols

df_dict

                 tamano vecindario  year  puntaje  precio
Baker House        7420    BrkSide  1939        5  118000
Beazley House     14115    Mitchel  1993        5  143000
Dominguez House   14260    NoRidge  2000        8  250000
Hamilton House     6120    OldTown  1931        7  129900
James House       11250    CollgCr  2001        7  223500
Martinez House     9600    Veenker  1976        6  181500
Roberts House      9550    Crawfor  1915        7  140000
Smith House        8450    CollgCr  2003        7  208500
Snyder House      10084    Somerst  2004        8  307000
Zuckerman House   10382     NWAmes  1973        7  200000

In [67]:
df_dict = df_dict.reset_index()
df_dict = df_dict.rename(columns = {"index":"nombre_casa"})
df_dict

  nombre_casa      nombre_casa  tamano vecindario  year  puntaje  precio
0           0      Baker House    7420    BrkSide  1939        5  118000
1           1    Beazley House   14115    Mitchel  1993        5  143000
2           2  Dominguez House   14260    NoRidge  2000        8  250000
3           3   Hamilton House    6120    OldTown  1931        7  129900
4           4      James House   11250    CollgCr  2001        7  223500
5           5   Martinez House    9600    Veenker  1976        6  181500
6           6    Roberts House    9550    Crawfor  1915        7  140000
7           7      Smith House    8450    CollgCr  2003        7  208500
8           8     Snyder House   10084    Somerst  2004        8  307000
9           9  Zuckerman House   10382     NWAmes  1973        7  200000

In [68]:
df_dict["precio"].mean() #promedio

190140.0

In [69]:
import os

In [70]:
from google.colab import drive

In [81]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [82]:
os.getcwd()

'/content'

In [89]:
!ls "/content/drive/my drive"

ls: cannot access '/content/drive/my drive': No such file or directory

In [90]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [91]:
!ls /content/drive/

MyDrive

In [92]:
!ls '/content/drive/My Drive'

 Clase2  'Colab Notebooks'   marbetes.gsheet  'rafael cv.pdf'

In [93]:
!ls '/content/drive/My Drive/Clase2'

vehicles.csv  vehicles.json  vehicles_messy.csv  vehicles_pipe.txt  vehicles_tab.txt  vehicles.xlsx

In [97]:
path = '/content/drive/My Drive/Clase2'
files = os.listdir(path)
files

['vehicles.xlsx',
 'vehicles.json',
 'vehicles_messy.csv',
 'vehicles_tab.txt',
 'vehicles.csv',
 'vehicles_pipe.txt']

In [100]:
files_paths = [f"{path}{i}" for i in files]
files_paths

['/content/drive/My Drive/Clase2vehicles.xlsx',
 '/content/drive/My Drive/Clase2vehicles.json',
 '/content/drive/My Drive/Clase2vehicles_messy.csv',
 '/content/drive/My Drive/Clase2vehicles_tab.txt',
 '/content/drive/My Drive/Clase2vehicles.csv',
 '/content/drive/My Drive/Clase2vehicles_pipe.txt']

In [104]:
df_csv = pd.read_csv('/content/drive/My Drive/Clase2/vehicles_messy.csv')
df_csv

<ipython-input-104-b77d869d22c8>:1: DtypeWarning: Columns (70,71,72,73,74,76,79) have mixed types. Specify dtype option on import or set low_memory=False.
  df_csv = pd.read_csv('/content/drive/My Drive/Clase2/vehicles_messy.csv')

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37839,14.330870,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37840,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37841,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37842,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [106]:
tf_csv = pd.read_csv('/content/drive/My Drive/Clase2/vehicles_pipe.txt', sep='|')
tf_csv

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

# Sección nueva